server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # React/Vite router'ı için sayfa yenilemede 404 hatasını çözer
        try_files $uri $uri/ /index.html;
    }
}